spring:
  application:
    name: ms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/clients
  profiles:
    active: local

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true